---
title: "Dashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
    source: embed
---

```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(p8105.datasets)
library(plotly)
```

```{r}
data("ny_noaa")

nys_weather = 
  ny_noaa %>%
  sample_n(20000) %>% 
  janitor::clean_names() %>%
  separate(date, into = c("year", "month", "day"), sep = "-", convert = TRUE)%>%
  mutate(month = month.abb[month], 
         prcp = prcp/10, 
         tmax = as.numeric(tmax),
         tmin = as.numeric(tmin)
  ) %>% 
  select(id, day, month, year, everything()) %>% 
  mutate(
    tmax = tmax/10,
    tmin = tmin/10
    )
```

Column {data-width=650}
-----------------------------------------------------------------------

### Chart A - Scatterplot of `tmax` vs. `tmin`
```{r}
nys_weather %>% 
  plot_ly(
    x = ~tmin, y = ~tmax, color = ~month,
    alpha = .5, type = "scatter", mode = "markers", colors = "viridis"
  )%>%
  plotly::layout(yaxis = list(title = 'tmax (C)'),
         xaxis = list(title = 'tmin (C)'))
```

Column {data-width=350}
-----------------------------------------------------------------------

### Chart B - Maximum monthly temperatures recorded across 5-years (2006-2010)
```{r}
nys_weather %>% 
  group_by(month, year)%>%
  filter(year %in% (2006:2010))%>%
  summarise(max_temp = max(tmax, na.rm = TRUE))%>%
  plot_ly(
    x = ~year, y = ~max_temp, color = ~month,
    alpha = .5, type = "scatter", mode = "line", colors = "viridis"
  )%>% 
  layout(yaxis = list(title = 'Maximum Temperature (C)'),
         xaxis = list(title = 'Year'))
```

### Chart C - Maximum monthly precipitation recorded in 2010
```{r}
nys_weather %>% 
  group_by(month, year)%>%
  filter(year %in% (2010))%>%
  summarise(max_prcp = max(prcp, na.rm = TRUE))%>%
  plot_ly(
    x = ~year, y = ~max_prcp, color = ~month, 
    alpha = .5, type = "bar", colors = "viridis"
  )%>% 
  layout(yaxis = list(title = 'Maximum Precipitation (mm)'),
         xaxis = list(title = 'Year'))
```

